name: CD

on:
  push:
    branches:
      - main

jobs:
  access-vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/tiktok-ecommerce
            which node
            node --version
            env
            npm run build
            echo "Successfully deployed"
