name: CD

on:
  push:
    branches:
      - main

jobs:
  access-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Commands to run on the VM after SSHing in
            echo "Successfully SSHed into VM on branch merge to main."
