name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Set PATH
        run: echo "export PATH=\$PATH:/root/.nvm/versions/node/v20.9.0/bin/pm2" >> $GITHUB_ENV
      - name: Debug Environment
        run: |
          echo "PATH: $PATH"
          echo "SHELL: $SHELL"
        shell: bash
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc -i --delete'
          SOURCE: '.next/'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: '/var/www/tiktok-ecommerce/.next'
          EXCLUDE: '/.next/, /node_modules/'
          SCRIPT_BEFORE: ls
          SCRIPT_AFTER: |
            node --version
            pm2 restart tiktok-ecommerce
